let json = {
    "tg": "Togo",
    "me": "Montenegro",
    "la": "Laos",
    "mr": "Mauritania",
    "ni": "Nicaragua",
    "lv": "Latvia",
    "om": "Oman",
    "af": "Afghanistan",
    "cy": "Cyprus",
    "bj": "Benin",
    "aq": "Antarctica",
    "cn": "China",
    "gb-sct": "Scotland",
    "co": "Colombia",
    "cx": "Christmas Island",
    "ag": "Antigua and Barbuda",
    "ms": "Montserrat",
    "md": "Moldova",
    "zm": "Zambia",
    "vn": "Vietnam",
    "tf": "French Southern and Antarctic Lands",
    "td": "Chad",
    "yt": "Mayotte",
    "lb": "Lebanon",
    "mf": "Saint Martin",
    "lu": "Luxembourg",
    "mq": "Martinique",
    "cz": "Czechia",
    "ae": "United Arab Emirates",
    "cm": "Cameroon",
    "bi": "Burundi",
    "ar": "Argentina",
    "as": "American Samoa",
    "bh": "Bahrain",
    "cl": "Chile",
    "ad": "Andorra",
    "mp": "Northern Mariana Islands",
    "lt": "Lithuania",
    "mg": "Madagascar",
    "lc": "Saint Lucia",
    "tr": "Turkey",
    "ua": "Ukraine",
    "tv": "Tuvalu",
    "vi": "U.S. Virgin Islands",
    "mt": "Malta",
    "no": "Norway",
    "mc": "Monaco",
    "ch": "Switzerland",
    "bl": "Saint Barthélemy",
    "aw": "Aruba",
    "bz": "Belize",
    "bm": "Bermuda",
    "ci": "Ivory Coast",
    "mu": "Mauritius",
    "us": "United States",
    "tw": "Taiwan",
    "ye": "Yemen",
    "mw": "Malawi",
    "nl": "Netherlands",
    "ls": "Lesotho",
    "bo": "Bolivia",
    "at": "Austria",
    "ck": "Cook Islands",
    "by": "Belarus",
    "au": "Australia",
    "bn": "Brunei",
    "ma": "Morocco",
    "nz": "New Zealand",
    "lr": "Liberia",
    "mv": "Maldives",
    "tc": "Turks and Caicos Islands",
    "ug": "Uganda",
    "tt": "Trinidad and Tobago",
    "pl": "Poland",
    "rs": "Serbia",
    "in": "India",
    "ge": "Georgia",
    "gr": "Greece",
    "gs": "South Georgia and the South Sandwich Islands",
    "gd": "Grenada",
    "io": "British Indian Ocean Territory",
    "hk": "Hong Kong",
    "kp": "North Korea",
    "gb-nir": "Northern Ireland",
    "kg": "Kyrgyzstan",
    "pm": "Saint Pierre and Miquelon",
    "sv": "El Salvador",
    "re": "Réunion",
    "sa": "Saudi Arabia",
    "sc": "Seychelles",
    "st": "São Tomé and Príncipe",
    "ke": "Kenya",
    "im": "Isle of Man",
    "kr": "South Korea",
    "gf": "French Guiana",
    "dj": "Djibouti",
    "gq": "Equatorial Guinea",
    "gp": "Guadeloupe",
    "dk": "Denmark",
    "gg": "Guernsey",
    "il": "Israel",
    "pn": "Pitcairn Islands",
    "sb": "Solomon Islands",
    "py": "Paraguay",
    "ru": "Russia",
    "kw": "Kuwait",
    "do": "Dominican Republic",
    "gt": "Guatemala",
    "gb": "United Kingdom",
    "gu": "Guam",
    "je": "Jersey",
    "hm": "Heard Island and McDonald Islands",
    "sg": "Singapore",
    "pk": "Pakistan",
    "sr": "Suriname",
    "se": "Sweden",
    "jp": "Japan",
    "gw": "Guinea-Bissau",
    "eh": "Western Sahara",
    "dz": "Algeria",
    "ga": "Gabon",
    "fr": "France",
    "dm": "Dominica",
    "hn": "Honduras",
    "sd": "Sudan",
    "rw": "Rwanda",
    "ph": "Philippines",
    "ss": "South Sudan",
    "qa": "Qatar",
    "pe": "Peru",
    "pr": "Puerto Rico",
    "si": "Slovenia",
    "ht": "Haiti",
    "es": "Spain",
    "gl": "Greenland",
    "gm": "Gambia",
    "er": "Eritrea",
    "fi": "Finland",
    "ee": "Estonia",
    "kn": "Saint Kitts and Nevis",
    "hu": "Hungary",
    "iq": "Iraq",
    "ky": "Cayman Islands",
    "sh": "Saint Helena, Ascension and Tristan da Cunha",
    "ps": "Palestine",
    "pf": "French Polynesia",
    "sj": "Svalbard and Jan Mayen",
    "id": "Indonesia",
    "is": "Iceland",
    "eg": "Egypt",
    "fk": "Falkland Islands",
    "fj": "Fiji",
    "gn": "Guinea",
    "gy": "Guyana",
    "ir": "Iran",
    "km": "Comoros",
    "ie": "Ireland",
    "kz": "Kazakhstan",
    "ro": "Romania",
    "sk": "Slovakia",
    "pg": "Papua New Guinea",
    "pt": "Portugal",
    "so": "Somalia",
    "sx": "Sint Maarten",
    "hr": "Croatia",
    "ki": "Kiribati",
    "jm": "Jamaica",
    "ec": "Ecuador",
    "et": "Ethiopia",
    "fo": "Faroe Islands",
    "kh": "Cambodia",
    "sy": "Syria",
    "sn": "Senegal",
    "pw": "Palau",
    "sl": "Sierra Leone",
    "gb-eng": "England",
    "fm": "Micronesia",
    "gi": "Gibraltar",
    "de": "Germany",
    "gh": "Ghana",
    "jo": "Jordan",
    "it": "Italy",
    "pa": "Panama",
    "sz": "Eswatini",
    "sm": "San Marino",
    "tn": "Tunisia",
    "ml": "Mali",
    "cg": "Republic of the Congo",
    "ax": "Åland Islands",
    "ao": "Angola",
    "bt": "Bhutan",
    "bb": "Barbados",
    "cf": "Central African Republic",
    "mm": "Myanmar",
    "li": "Liechtenstein",
    "na": "Namibia",
    "mz": "Mozambique",
    "to": "Tonga",
    "vg": "British Virgin Islands",
    "ve": "Venezuela",
    "tz": "Tanzania",
    "tm": "Turkmenistan",
    "mx": "Mexico",
    "nc": "New Caledonia",
    "mo": "Macao",
    "lk": "Sri Lanka",
    "cd": "Democratic Republic of the Congo",
    "al": "Albania",
    "bw": "Botswana",
    "cr": "Costa Rica",
    "bv": "Bouvet Island",
    "am": "Armenia",
    "az": "Azerbaijan",
    "ba": "Bosnia and Herzegovina",
    "mn": "Mongolia",
    "nu": "Niue",
    "my": "Malaysia",
    "tl": "Timor-Leste",
    "ws": "Samoa",
    "th": "Thailand",
    "xk": "Kosovo",
    "nf": "Norfolk Island",
    "ly": "Libya",
    "ai": "Anguilla",
    "br": "Brazil",
    "cv": "Cape Verde",
    "be": "Belgium",
    "ca": "Canada",
    "bd": "Bangladesh",
    "cw": "Curaçao",
    "bs": "Bahamas",
    "ng": "Nigeria",
    "mk": "North Macedonia",
    "np": "Nepal",
    "va": "Vatican City",
    "uz": "Uzbekistan",
    "um": "United States Minor Outlying Islands",
    "tk": "Tokelau",
    "vc": "Saint Vincent and the Grenadines",
    "zw": "Zimbabwe",
    "nr": "Nauru",
    "ne": "Niger",
    "cu": "Cuba",
    "bq": "Bonaire, Sint Eustatius, and Saba",
    "bf": "Burkina Faso",
    "bg": "Bulgaria",
    "cc": "Cocos (Keeling) Islands",
    "gb-wls": "Wales",
    "mh": "Marshall Islands",
    "za": "South Africa",
    "uy": "Uruguay",
    "wf": "Wallis and Futuna",
    "vu": "Vanuatu",
    "tj": "Tajikistan",
    "agender": "Agender Pride",
    "ally": "Ally Pride",
    "aromantic": "Aromantic Pride",
    "asexual": "Asexual Pride",
    "bisexual": "Bisexual Pride",
    "butch": "Butch Lesbian Pride",
    "colorado": "Colorado Pride",
    "demiromantic": "Demiromantic Pride",
    "demisexual": "Demisexual Pride",
    "genderfluid": "Genderfluid Pride",
    "genderqueer": "GenderQueer Pride",
    "intersex": "Intersex Pride",
    "labrys": "Labrys Lesbian Pride",
    "lesbian": "Lesbian Pride",
    "nonbinary": "Non-Binary Pride",
    "pansexual": "Pansexual Pride",
    "philly": "Philidelphia Pride",
    "polyamorous": "Polyamorous Pride",
    "polysexual": "Polysexual Pride",
    "progress": "Progress Pride",
    "rainbow": "Rainbow Pride",
    "transgender": "Transgender Pride",
    "two-spirit": "Two Spirit Pride"
};

let images = {};
let boykisser;

function preload() {
    for (let i in json) {
        images[i] = loadImage('flags/' + i + '.png');
    }
    boykisser = loadImage('boykissertr.png');
}

function setup() {
    createCanvas(boykisser.width / 2, boykisser.height / 2);
    imageMode(CENTER);
    for (let i in json) {
        let option = document.createElement('option');
        option.value = i;
        option.innerHTML = json[i];
        document.querySelector('#flags').appendChild(option);
    }
    document.querySelector("#loader").remove();
}

document.querySelector("#generate").addEventListener("click", () => {
    let img = images[document.querySelector("#flags").value];
    let aspectRatio = img.width / img.height;
    let dWidth = height * aspectRatio;
    image(img, width / 2, height / 2, dWidth, height);
    image(boykisser, width / 2, height / 2, width, height);
});